name: "Build & Push"

on:
  workflow_run:
    workflows:
      - "Checks"
    branches:
      - "main"
    types:
      - "completed"

jobs:
  build:
    name: "Build & Push"
    runs-on: "ubuntu-18.04"

    # Only if checks succeeded.
    if: "${{ github.event.workflow_run.conclusion == 'success' }}"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Expose short revision SHA"
        id: "get_sha"
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: "Log in to GHCR"
        uses: "docker/login-action@v1"
        with:
          registry: "ghcr.io"
          username: "kwzrd"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v1"

      - name: "Build & Push"
        uses: "docker/build-push-action@v2"
        with:
          context: "."
          tags: |
            "ghcr.io/kwzrd/ryan:latest"
            "ghcr.io/kwzrd/ryan:${{ steps.get_sha.outputs.sha_short }}"
          push: true
          build-args: "GIT_SHA=${{ steps.get_sha.outputs.sha_short }}"
