name: "Deployment"

on:
  workflow_run:
    workflows:
      - "Build & Push"
    branches:
      - "main"
    types:
      - "completed"

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-18.04"

    # Only if build succeeded.
    if: "${{ github.event.workflow_run.conclusion == 'success' }}"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Copy Compose file"
        uses: "appleboy/scp-action@v0.1.1"
        with:
          host: "${{ secrets.LINODE_HOST }}"
          username: "${{ secrets.LINODE_USERNAME }}"
          password: "${{ secrets.LINODE_PASSWORD }}"
          source: "docker-compose.yml"
          target: "~/ryan/"
          rm: false

      - name: "Restart services"
        uses: "appleboy/ssh-action@v0.1.4"
        with:
          host: "${{ secrets.LINODE_HOST }}"
          username: "${{ secrets.LINODE_USERNAME }}"
          password: "${{ secrets.LINODE_PASSWORD }}"
          script: "cd ryan && docker-compose down && docker-compose pull && docker-compose up -d"
